# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

proxy_delta <- function(Y, X, tau, beta_in, weights, model, delta, lambda, PeltyD, maxint1, maxint2, threshold) {
    .Call('_qrmono_proxy_delta', PACKAGE = 'qrmono', Y, X, tau, beta_in, weights, model, delta, lambda, PeltyD, maxint1, maxint2, threshold)
}

proxy_xi <- function(Y, X, tau, beta_in, weights, model, eps, lambda, PeltyD, maxint1, maxint2, threshold) {
    .Call('_qrmono_proxy_xi', PACKAGE = 'qrmono', Y, X, tau, beta_in, weights, model, eps, lambda, PeltyD, maxint1, maxint2, threshold)
}

checkloss <- function(res, tau) {
    .Call('_qrmono_checkloss', PACKAGE = 'qrmono', res, tau)
}

proxy_inital <- function(Y, X, tau, weights, model, delta, lambda, PeltyD, maxint1, maxint2, threshold) {
    .Call('_qrmono_proxy_inital', PACKAGE = 'qrmono', Y, X, tau, weights, model, delta, lambda, PeltyD, maxint1, maxint2, threshold)
}

